services:
    php:
        container_name: framework-php
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 80:80
            - 443:443
            - 5173:5173
            - 5174:5174
            - 4321:4321
        environment:
            - XDEBUG_PORT=9000
            - XDEBUG_CLIENT_HOST=host.docker.internal
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
        networks:
            - lion

    mysql:
        image: mysql
        container_name: framework-mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: lion_database
            MYSQL_PASSWORD: lion
            MYSQL_ROOT_PASSWORD: lion
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion

volumes:
    mysql_data:

networks:
    lion:
        driver: bridge
