services:
    app:
        container_name: framework-app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DISPLAY=${DISPLAY}
            - DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
        devices:
            - /dev/dri:/dev/dri
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8080:8080"
            - "5173:5173"
        volumes:
            - ./:/var/www/html
            - /var/run/dbus:/var/run/dbus
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/dri:/dev/dri
        depends_on:
            - mysql
            - phpmyadmin
            - redis
        cap_add:
            - SYS_ADMIN
        networks:
            - lion
    redis:
        image: redis
        container_name: framework-redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/var/lib/redis
        environment:
            REDIS_HOST: redis
            REDIS_PASSWORD: lion
            REDIS_DATABASES: 1
        networks:
            - lion
    mailhog:
        image: mailhog/mailhog
        container_name: framework-mailhog
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - lion
    mysql:
        image: mysql
        container_name: framework-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: lion_database
            MYSQL_PASSWORD: lion
            MYSQL_ROOT_PASSWORD: lion
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: framework-phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 80:80
        environment:
            PMA_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: lion
            MYSQL_ROOT_PASSWORD: lion
        networks:
            - lion
volumes:
    mysql_data:
    redis_data:
        driver: local
networks:
    lion:
        driver: bridge
