name: Lion-Framework (CI Workflow)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 0 * * *"

jobs:
  composer-validation:
    runs-on: ubuntu-latest
    name: Composer Validation

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, gd, zip

      - name: Composer Install
        run: composer install

      - name: Composer Validate
        run: composer validate --strict

      - name: Composer Check for vulnerabilities
        run: composer audit --locked

      - name: Composer Dump-Autoload
        run: composer dump-autoload --optimize --strict-psr

  code-analyze:
    runs-on: ubuntu-latest
    name: PHP Code Analyze
    needs:
      - composer-validation

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, gd, zip

      - name: Composer Install
        run: composer install

      - name: PHP CodeSnifer (App)
        run: php -d memory_limit=-1 vendor/bin/phpcs --standard=PSR12 app

      - name: PHP CodeSnifer (Database)
        run: php -d memory_limit=-1 vendor/bin/phpcs --standard=PSR12 database

      - name: PHP CodeSnifer (Tests)
        run: php -d memory_limit=-1 vendor/bin/phpcs --standard=PSR12 --ignore=tests/build/\*,tests/bootstrap.php --colors tests

        # - name: PHPStan (Src)
        # run: php -d memory_limit=-1 vendor/bin/phpstan analyse --level max src

  tests:
    runs-on: ubuntu-latest
    name: PHP Tests
    needs:
      - composer-validation
      - code-analyze

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      mysql:
        image: mysql
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: lion_database
          MYSQL_ROOT_PASSWORD: lion
          MYSQL_PASSWORD: lion

      mailhog:
        image: mailhog/mailhog
        ports:
          - 8025:8025
          - 1025:1025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, gd, zip, pdo, pdo_mysql, pdo_pgsql, redis, xdebug
          coverage: xdebug
          ini-values: |
            xdebug.mode=develop,coverage,debug
            xdebug.start_with_request=yes
            xdebug.log_level=0
          tools: composer

      - name: Copy .env.actions to .env
        run: |
          if [ -f .env.actions ]; then
            cp .env.actions .env
          else
            echo ".env.actions not found! Please make sure the file exists."
            exit 1
          fi

      - name: Install php dependencies
        run: composer install

      - name: Start PHP built-in server
        run: nohup php -S 0.0.0.0:8000 -t public &

      - name: Generate RSA Key's
        run: php lion new:rsa

      - name: Run tests
        run: php lion test
