name: Lion-Framework (CI Workflow)

on:
  push:
    branches:
      - php-actions
  pull_request:
    branches:
      - 5.x
    paths:
     - '.github/workflows/php.yml'
     - 'app/**'
     - 'config/**'
     - 'database/**'
     - 'routes/**'
     - 'storage/**'
     - 'tests/**'
     - '.env.actions'
     - 'composer.json'
     - 'composer.lock'
     - 'phpunit.xml'

env:
  PHP_VERSION: 8.5

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    name: Install PHP Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, gd, zip

      - name: Install PHP dependencies
        run: composer install

      - name: Cache vendor directory
        uses: actions/cache@v5
        with:
          path: vendor
          key: php-vendor-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-vendor-${{ runner.os }}-${{ github.run_id }}

  composer-validation:
    runs-on: ubuntu-latest
    name: Composer Validation
    needs: install-dependencies

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, gd, zip

      - name: Restore vendor directory from cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: php-vendor-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-vendor-${{ runner.os }}-${{ github.run_id }}

      - name: Composer Validate
        run: composer validate --strict

      - name: Composer Check for vulnerabilities
        run: composer audit --locked

      - name: Composer Dump-Autoload
        run: composer dump-autoload --optimize --strict-psr

  dependency-review:
    runs-on: ubuntu-latest
    name: Dependency Review
    needs: install-dependencies

    permissions:
      pull-requests: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ github.event.repository.default_branch }}
          head-ref: ${{ github.sha }}
          comment-summary-in-pr: true
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: critical
          license-check: true
